name: scraping-api

services:

  web:
    build: ./app
    ports:
      - ${WEB_PORT:-8080}:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-cloud}:${POSTGRES_PASSWORD:-cloudpassword}@db:${DB_PORT:-5430}/${DB_NAME:-cloud}
      SECRET_KEY: ${SECRET_KEY:-cloudkey}

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: 
      - -p ${DB_PORT:-5430}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cloudpassword}

volumes:
      postgres_data: 